dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
  apt:
    sources:
      - google-chrome

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run e2e # -- --protractor-config=e2e/protractor-ci.conf.js
  - npm run lint
