jobs:
  test:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies (npm install)
          command: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Add useCache to the leaflet TileLayerOptions
          command: |
            cd node_modules/@types/leaflet
            LINENUMBER=$(($(awk '/interface TileLayerOptions/{ print NR; exit }' index.d.ts)+1))i
            sed -i "$LINENUMBER useCache?: boolean;" index.d.ts
      - run: 
          name: Build project
          command: npm run start
      - run: 
          name: Run tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
      - run: 
          name: Run linting
          command: npm run lint
  deploy:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies (npm install)
          command: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Add useCache to the leaflet TileLayerOptions
          command: |
            cd node_modules/@types/leaflet
            LINENUMBER=$(($(awk '/interface TileLayerOptions/{ print NR; exit }' index.d.ts)+1))i
            sed -i "$LINENUMBER useCache?: boolean;" index.d.ts
      - run:
          name: Build
          command: npm run-script build
      - run:
          name: Check if dist directory exists
          command: ls && ls dist && ls dist/WingmanMapsComponent
      - run: 
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
      # - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
              - test
          filters:
            branches:
              only:
                - development
                - master