version: 2
jobs:
  build-job:
    docker:
      -image: circleci/node:10.8.0
    
      working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn run build
    
      - save_cache:
        paths:
          - node_modules
          - dist
          - package.json
          - firebase.json
          - .firebaserc
        key: v1-dist-{{ "package.json" }}
      
      - run: yarn run test:unit
  
  deploy-job:
    docker:
      -image: circleci/node:10.8.0
    working-directory: ~/repo
    
    steps:
      - restore_cache:
        keys:
          - v1-dist-{{ "package.json" }}
      - run:
          name: show directory
          command: pwd
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: look in direectory
          command: ls -ltr
      - run:
          name: Deploy master to firebase
          command: npm run firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master